steps:
  - id: pull-api-image
    name: gcr.io/cloud-builders/docker
    entrypoint: bash
    waitFor: ["-"]
    args:
      - -c
      - docker pull ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPOSITORY}/${_API_IMAGE}:latest || exit 0

  - id: pull-cli-image
    name: gcr.io/cloud-builders/docker
    entrypoint: bash
    waitFor: ["-"]
    args:
      - -c
      - docker pull ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPOSITORY}/${_CLI_IMAGE}:latest || exit 0

  - id: pull-db-migrate-image
    name: gcr.io/cloud-builders/docker
    entrypoint: bash
    waitFor: ["-"]
    args:
      - -c
      - docker pull ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPOSITORY}/${_DB_MIGRATE_IMAGE}:latest || exit 0

  - id: pull-admin-image
    name: gcr.io/cloud-builders/docker
    entrypoint: bash
    waitFor: ["-"]
    args:
      - -c
      - docker pull ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPOSITORY}/${_ADMIN_IMAGE}:latest || exit 0

  - id: pull-viewer-image
    name: gcr.io/cloud-builders/docker
    entrypoint: bash
    waitFor: ["-"]
    args:
      - -c
      - docker pull ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPOSITORY}/${_VIEWER_IMAGE}:latest || exit 0

  - id: pull-admin-proxy-image
    name: gcr.io/cloud-builders/docker
    entrypoint: bash
    waitFor: ["-"]
    args:
      - -c
      - docker pull ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPOSITORY}/${_ADMIN_PROXY_IMAGE}:latest || exit 0

  - id: pull-discord-notifier-image
    name: gcr.io/cloud-builders/docker
    entrypoint: bash
    waitFor: ["-"]
    args:
      - -c
      - docker pull ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPOSITORY}/${_DISCORD_NOTIFIER_IMAGE}:latest || exit 0

  - id: build-api-image
    name: gcr.io/cloud-builders/docker
    waitFor:
      - pull-api-image
    args:
      - build
      - -f
      - infra/staging/docker/api/Dockerfile
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPOSITORY}/${_API_IMAGE}:$COMMIT_SHA
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPOSITORY}/${_API_IMAGE}:latest
      - --cache-from
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPOSITORY}/${_API_IMAGE}:latest
      - .

  - id: build-cli-image
    name: gcr.io/cloud-builders/docker
    waitFor:
      - pull-cli-image
    args:
      - build
      - -f
      - infra/staging/docker/cli/Dockerfile
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPOSITORY}/${_CLI_IMAGE}:$COMMIT_SHA
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPOSITORY}/${_CLI_IMAGE}:latest
      - --cache-from
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPOSITORY}/${_CLI_IMAGE}:latest
      - .

  - id: build-db-migrate-image
    name: gcr.io/cloud-builders/docker
    waitFor:
      - pull-db-migrate-image
    args:
      - build
      - -f
      - infra/staging/docker/db-migrate/Dockerfile
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPOSITORY}/${_DB_MIGRATE_IMAGE}:$COMMIT_SHA
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPOSITORY}/${_DB_MIGRATE_IMAGE}:latest
      - --cache-from
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPOSITORY}/${_DB_MIGRATE_IMAGE}:latest
      - .

  - id: build-discord-notifier-image
    name: gcr.io/cloud-builders/docker
    waitFor:
      - pull-discord-notifier-image
    args:
      - build
      - -f
      - infra/staging/docker/discord-notifier/Dockerfile
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPOSITORY}/${_DISCORD_NOTIFIER_IMAGE}:$COMMIT_SHA
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPOSITORY}/${_DISCORD_NOTIFIER_IMAGE}:latest
      - --cache-from
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPOSITORY}/${_DISCORD_NOTIFIER_IMAGE}:latest
      - .

  - id: build-admin-image
    name: gcr.io/cloud-builders/docker
    waitFor:
      - pull-admin-image
    args:
      - build
      - -f
      - infra/staging/docker/admin/Dockerfile
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPOSITORY}/${_ADMIN_IMAGE}:$COMMIT_SHA
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPOSITORY}/${_ADMIN_IMAGE}:latest
      - --cache-from
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPOSITORY}/${_ADMIN_IMAGE}:latest
      - --build-arg
      - PUBLIC_APP_URL=${_PUBLIC_APP_URL}
      - .

  - id: build-viewer-image
    name: gcr.io/cloud-builders/docker
    waitFor:
      - pull-viewer-image
    args:
      - build
      - -f
      - infra/staging/docker/viewer/Dockerfile
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPOSITORY}/${_VIEWER_IMAGE}:$COMMIT_SHA
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPOSITORY}/${_VIEWER_IMAGE}:latest
      - --cache-from
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPOSITORY}/${_VIEWER_IMAGE}:latest
      - .

  - id: build-admin-proxy-image
    name: gcr.io/cloud-builders/docker
    waitFor:
      - pull-admin-proxy-image
    args:
      - build
      - -f
      - infra/staging/docker/admin-proxy/Dockerfile
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPOSITORY}/${_ADMIN_PROXY_IMAGE}:$COMMIT_SHA
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPOSITORY}/${_ADMIN_PROXY_IMAGE}:latest
      - --cache-from
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPOSITORY}/${_ADMIN_PROXY_IMAGE}:latest
      - .

  - id: push-api-image
    name: gcr.io/cloud-builders/docker
    waitFor:
      - build-api-image
    args:
      - push
      - --all-tags
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPOSITORY}/${_API_IMAGE}

  - id: push-cli-image
    name: gcr.io/cloud-builders/docker
    waitFor:
      - build-cli-image
    args:
      - push
      - --all-tags
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPOSITORY}/${_CLI_IMAGE}

  - id: push-db-migrate-image
    name: gcr.io/cloud-builders/docker
    waitFor:
      - build-db-migrate-image
    args:
      - push
      - --all-tags
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPOSITORY}/${_DB_MIGRATE_IMAGE}

  - id: push-admin-image
    name: gcr.io/cloud-builders/docker
    waitFor:
      - build-admin-image
    args:
      - push
      - --all-tags
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPOSITORY}/${_ADMIN_IMAGE}

  - id: push-viewer-image
    name: gcr.io/cloud-builders/docker
    waitFor:
      - build-viewer-image
    args:
      - push
      - --all-tags
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPOSITORY}/${_VIEWER_IMAGE}

  - id: push-admin-proxy-image
    name: gcr.io/cloud-builders/docker
    waitFor:
      - build-admin-proxy-image
    args:
      - push
      - --all-tags
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPOSITORY}/${_ADMIN_PROXY_IMAGE}

  - id: push-discord-notifier-image
    name: gcr.io/cloud-builders/docker
    waitFor:
      - build-discord-notifier-image
    args:
      - push
      - --all-tags
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPOSITORY}/${_DISCORD_NOTIFIER_IMAGE}

  # TODO マイグレーションを別で行う
  - id: deploy-db-migrate-job
    name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    waitFor:
      - push-db-migrate-image
    args:
      - run
      - jobs
      - deploy
      - stg-db-migrate
      - --image
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPOSITORY}/${_DB_MIGRATE_IMAGE}:$COMMIT_SHA
      - --region
      - ${_REGION}
      - --service-account
      - ${_JOB_SERVICE_ACCOUNT}
      # - --wait
      - --quiet

  - id: deploy-admin-invite
    name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    waitFor:
      - push-cli-image
    args:
      - run
      - jobs
      - deploy
      - stg-admin-invite
      - --image
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPOSITORY}/${_CLI_IMAGE}:$COMMIT_SHA
      - --region
      - ${_REGION}
      - --service-account
      - ${_JOB_SERVICE_ACCOUNT}
      - --quiet

  - id: deploy-media-youtube-import
    name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    waitFor:
      - push-cli-image
    args:
      - run
      - jobs
      - deploy
      - stg-media-youtube-import
      - --image
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPOSITORY}/${_CLI_IMAGE}:$COMMIT_SHA
      - --region
      - ${_REGION}
      - --service-account
      - ${_JOB_SERVICE_ACCOUNT}
      - --command
      - php,artisan,media:youtube:import
      - --quiet

  - id: deploy-api
    name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    waitFor:
      - push-api-image
    args:
      - run
      - deploy
      - stg-isekai-api
      - --image
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPOSITORY}/${_API_IMAGE}:$COMMIT_SHA
      - --region
      - ${_REGION}
      - --service-account
      - ${_API_SERVICE_ACCOUNT}
      - --ingress
      - ${_API_INGRESS}
      - --scaling=auto
      - --max=1
      - --quiet

  - id: deploy-discord-notifier
    name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    waitFor:
      - push-discord-notifier-image
    args:
      - run
      - deploy
      - stg-isekai-discord-notifier
      - --image
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPOSITORY}/${_DISCORD_NOTIFIER_IMAGE}:$COMMIT_SHA
      - --region
      - ${_REGION}
      - --service-account
      - ${_NOTIFY_SERVICE_ACCOUNT}
      - --quiet

  - id: deploy-admin
    name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    waitFor:
      - push-admin-image
    args:
      - run
      - deploy
      - stg-isekai-admin
      - --image
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPOSITORY}/${_ADMIN_IMAGE}:$COMMIT_SHA
      - --region
      - ${_REGION}
      - --service-account
      - ${_ADMIN_SERVICE_ACCOUNT}
      - --ingress
      - ${_ADMIN_INGRESS}
      - --scaling=auto
      - --max=1
      - --quiet

  # TODO デプロイは別に行う
  - id: deploy-viewer
    name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    waitFor:
      - push-viewer-image
    args:
      - run
      - jobs
      - deploy
      - stg-viewer-deploy
      - --image
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPOSITORY}/${_VIEWER_IMAGE}:$COMMIT_SHA
      - --region
      - ${_REGION}
      - --service-account
      - ${_JOB_SERVICE_ACCOUNT}
      # - --wait
      - --quiet

  - id: deploy-admin-proxy
    name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    waitFor:
      - push-admin-proxy-image
    args:
      - run
      - jobs
      - deploy
      - stg-admin-proxy-deploy
      - --image
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPOSITORY}/${_ADMIN_PROXY_IMAGE}:$COMMIT_SHA
      - --region
      - ${_REGION}
      - --service-account
      - ${_JOB_SERVICE_ACCOUNT}
      - --wait
      - --quiet

options:
  logging: CLOUD_LOGGING_ONLY
  # 費用を抑えるためにスペックを下げる
  # 費用と効果が見合うかを改めて試算してから設定する
  # machineType: 'E2_HIGHCPU_8'
