name: Release QA

# main, stg 向け PR ではパスに関係なくすべての QA を実行する
on:
  pull_request:
    branches:
      - main
      - stg
  push:
    branches:
      - main
      - stg

permissions:
  contents: read
  packages: write

jobs:
  server:
    name: Server QA
    uses: ./.github/workflows/server-qa.yaml

  viewer:
    name: Viewer QA
    uses: ./.github/workflows/viewer-qa.yaml

  admin:
    name: Admin QA
    uses: ./.github/workflows/admin-qa.yaml

  contracts:
    name: Contracts QA
    uses: ./.github/workflows/contracts-qa.yaml

  discord-notifier:
    name: Discord Notifier QA
    uses: ./.github/workflows/discord-notifier-qa.yaml

  notify-publish:
    name: Notify Publish QA
    uses: ./.github/workflows/notify-publish-qa.yaml

  notify-contract:
    name: Notify Contract QA
    uses: ./.github/workflows/notify-contract-qa.yaml

  admin-proxy:
    name: Admin Proxy QA
    uses: ./.github/workflows/admin-proxy-qa.yaml

  public-api:
    name: Public API QA
    uses: ./.github/workflows/public-api-qa.yaml

  infra-docker:
    name: Infra Docker QA
    uses: ./.github/workflows/infra-docker-qa.yaml
